Added support for the node.roles configuration.
bitnami/bitnami-docker-elasticsearch pull request #91
Opened 2021-04-13 14:37 UTC by mhjtrifork

**Description of the change**

Added support for the node.roles configuration instead of the deprecated node.master and node.data options. The change should be compatible with existing deployments but setting the ELASTICEARCH_USE_NODE_ROLES option will ignore any ELASTICSEARCH_NODE_TYPE settings.

**Benefits**

Allows setting of all the specific node roles, enabling functionality such as ILM by using roles such as data_hot and data_warm.

**Possible drawbacks**

None

**Applicable issues**

N/A

**Additional information**

Only changed for ES 7 image.

2021-04-14 13:50 UTC, Mauraza requested changes
Hi @mhjtrifork,

Thanks for the PR! Could you check the comment?

2021-04-14 13:50 UTC, Mauraza commented on 7/debian-10/rootfs/opt/bitnami/scripts/libelasticsearch.sh
> -        [[ -d "${ELASTICSEARCH_BASE_DIR}/modules/x-pack-ml/platform/linux-x86_64/lib" ]] || elasticsearch_conf_set xpack.ml.enabled "false"
Could you add this line?
it's necessary

2021-04-14 14:05 UTC, mhjtrifork commented on 7/debian-10/rootfs/opt/bitnami/scripts/libelasticsearch.sh
> -        [[ -d "${ELASTICSEARCH_BASE_DIR}/modules/x-pack-ml/platform/linux-x86_64/lib" ]] || elasticsearch_conf_set xpack.ml.enabled "false"
Ups, missed that one. Added again.

2021-04-15 07:19 UTC, Mauraza commented
Hi @mhjtrifork,

I going to do some internal tests to check that everything goes well. we will update the thread with the results.

2021-04-15 07:22 UTC, mhjtrifork commented
> Hi @mhjtrifork,
> 
> I going to do some internal tests to check that everything goes well. we will update the thread with the results.

Great, thanks.

I will probably add a new PR today/tomorrow for supporting multiple data paths.

2021-10-05 09:13 UTC, Mauraza commented
Hi @mhjtrifork,

I going to do the test with the new changes. Thanks for the PR!

2021-12-27 23:27 UTC, marcosbc commented
Removing the `on-hold` in order to unblock this. @Mauraza could you check if this can be merged?

2021-12-30 13:52 UTC, Mauraza commented
I'm doing some tests, I will update the thread when this finish

2022-01-19 16:24 UTC, Mauraza commented
Hi @mhjtrifork,

I'm making some changes, we will merge this PR soon

2022-02-02 11:23 UTC, alemorcuq commented
We expect to have this merged in the following days.

2022-02-03 15:46 UTC, merged