Added support for multiple data paths.
bitnami/bitnami-docker-elasticsearch pull request #92
Opened 2021-04-15 09:40 UTC by mhjtrifork

**Description of the change**

Added support for multiple data paths using the ELASTICSEARCH_DATA_DIR_LIST environment variable. I.e. the data.paths variable in the Elasticsearch configuration.
The ELASTICSEARCH_DATA_DIR environment variable is ignored in this case.
Migration of old data is skipped if multiple paths are listed.
The change should be backwards compatible. 

**Benefits**

Enables using more than one data directory in the configuration and therefore more than one mounted volume.

**Possible drawbacks**

None

**Applicable issues**

N/A

**Additional information**

Skips migration.

2021-04-16 07:13 UTC, juan131 requested changes
Thanks so much for this great contribution @mhjtrifork !!!

Some generic comments:

- This env. variable should be properly documented in the README.md. See https://github.com/bitnami/bitnami-docker-elasticsearch#environment-variables
- Please apply the same changes to the branch 6

2021-04-16 07:20 UTC, mhjtrifork commented on 7/debian-10/rootfs/opt/bitnami/scripts/elasticsearch/run.sh
> +ARGS=("-p" "$ELASTICSEARCH_TMP_DIR/elasticsearch.pid")
The directories are written in the data.paths variable in the configuration file, so as far as I can see it shouldn't be necessary.

2021-04-19 07:19 UTC, juan131 commented on 6/debian-10/rootfs/opt/bitnami/scripts/elasticsearch/run.sh
> +ARGS=("-p" "$ELASTICSEARCH_TMP_DIR/elasticsearch.pid")
For the record, the `-Epath.data` flag is equivalent to configure `path.data` in the `elasticsearch.yml`, see:

- https://www.elastic.co/guide/en/elasticsearch/reference/7.x/modules-node.html#_node_data_path_settings

I don't think there's a problem on removing it since we're already configuring it in the configuration file.

2021-04-19 07:19 UTC, juan131 approved these changes
LGTM

2021-04-19 13:42 UTC, juan131 commented
I sent your changes for internal review (I'll keep you updated)

2021-04-19 13:50 UTC, mhjtrifork commented
> I sent your changes for internal review (I'll keep you updated)

Great, thanks.

2021-04-19 14:47 UTC, merged